version: 2
updates:
    - package-ecosystem: 'pip'
      directory: '/cli'
      schedule:
          interval: 'weekly'
      target-branch: 'staging'
      groups:
          python-dependencies:
              patterns:
                  - '*'

    - package-ecosystem: 'npm'
      directory: '/frontend'
      schedule:
          interval: 'weekly'
      target-branch: 'staging'
      groups:
          frontend-dependencies:
              patterns:
                  - '*'

    - package-ecosystem: 'npm'
      directory: '/backend'
      schedule:
          interval: 'weekly'
      target-branch: 'staging'
      groups:
          backend-dependencies:
              patterns:
                  - '*'

    - package-ecosystem: 'npm'
      directory: '/queueConsumer'
      schedule:
          interval: 'weekly'
      target-branch: 'staging'
      groups:
          queue-consumer-dependencies:
              patterns:
                  - '*'

    - package-ecosystem: 'npm'
      directory: '/docs'
      schedule:
          interval: 'weekly'
      target-branch: 'staging'
      groups:
          docs-dependencies:
              patterns:
                  - '*'

    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
      target-branch: 'staging'
      groups:
          github-actions-dependencies:
              patterns:
                  - '*'
