services:
    action_test_file_hash:
        image: rslethz/kleinkram_actions:file-hash-latest
        container_name: kleinkram-action-test-file-hash-test
        build:
            context: ./
            dockerfile: backend/tests/actions/file-hash/Dockerfile
        entrypoint: sh

    api-server:
        image: rslethz/kleinkram:api-server-latest
        container_name: kleinkram-api-server-test
        build:
            context: .
            dockerfile: docker/backend.Dockerfile
            target: production
        ports:
            - 127.0.0.1:${SERVER_PORT}:${SERVER_PORT}
        volumes:
            - ./backend/.endpoints:/app/backend/.endpoints
        environment:
            SEED: 'false'

            DEVBUILD: 'false'
            REDIS_HOST: 'redis'
        env_file:
            - .env
        networks:
            - webnet
            - privatenet
        depends_on:
            - database

    database:
        image: postgres:17
        container_name: kleinkram-postgres-test
        ports:
            - '5432:5432'
        networks:
            - privatenet
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        command: postgres -c hba_file=/etc/postgresql/pg_hba.conf
        volumes:
            - db_data_test:/var/lib/postgresql/data
            - ./docker/testing-pg_hba.conf:/etc/postgresql/pg_hba.conf

    minio:
        image: minio/minio
        container_name: kleinkram-minio-test
        volumes:
            - minio_data_test:/data
            - ./docker/minio-entrypoint.sh:/docker-entrypoint.sh:ro
        environment:
            MINIO_ROOT_USER: ${MINIO_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
            MINIO_PROMETHEUS_AUTH_TYPE: 'public'
            MINIO_DATA_BUCKET_NAME: ${MINIO_DATA_BUCKET_NAME}
            MINIO_DB_BUCKET_NAME: ${MINIO_DB_BUCKET_NAME}
            MINIO_ARTIFACTS_BUCKET_NAME: ${MINIO_ARTIFACTS_BUCKET_NAME}
            MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
            MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}

        entrypoint: ['/docker-entrypoint.sh']

        ports:
            - '127.0.0.1:9000:9000'
            - '127.0.0.1:9001:9001'
        networks:
            - webnet
            - privatenet

    frontend:
        image: rslethz/kleinkram:frontend-dev
        container_name: kleinkram-frontend-test

        build:
            context: .
            dockerfile: docker/frontend.Dockerfile
            args:
                - BACKEND_URL=${BACKEND_URL}
        ports:
            - '8003:8003'

        env_file:
            - .env

        networks:
            - webnet

    redis:
        image: redis:latest
        container_name: kleinkram-redis-test
        ports:
            - '6379:6379'
        networks:
            - privatenet

    queue-consumer:
        image: rslethz/kleinkram:queue-consumer-latest
        container_name: kleinkram-queue-consumer-test
        hostname: 'DO_NOT_CHANGE'
        build:
            context: .
            dockerfile: docker/queue-consumer.Dockerfile
            target: production
        volumes:
            # mount docker socket to access docker from within the container
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            REDIS_HOST: 'redis'
        env_file:
            - .env
        networks:
            - privatenet
        depends_on:
            - database

    fake-oauth:
        build: dev-oauth
        ports:
            - '8004:5000'
        networks:
            - privatenet
            - webnet

volumes:
    db_data_test:
    minio_data_test:
    logging-prometheus-storage:
    logging-tempo-data:
    vitepress_dist:
    node_modules:

networks:
    webnet:
    privatenet:
