services:
    action_test_file_hash:
        image: rslethz/kleinkram_actions:file-hash-latest
        container_name: kleinkram-action-test-file-hash
        build:
            context: ./
            dockerfile: backend/tests/actions/file-hash/Dockerfile
        entrypoint: sh

    api-server:
        image: rslethz/kleinkram:api-server-latest
        container_name: kleinkram-api-server
        build:
            context: .
            dockerfile: ./backend/prod.Dockerfile
        ports:
            - 127.0.0.1:${SERVER_PORT}:${SERVER_PORT}
        volumes:
            - ./backend/.endpoints:/usr/src/app/backend/.endpoints
        environment:
            SEED: 'false'
            DEVBUILD: 'false'
        env_file:
            - .env
        networks:
            - webnet
            - privatenet
        depends_on:
            - database

    database:
        image: postgres:16
        container_name: kleinkram-postgres
        ports:
            - '5432:5432'
        networks:
            - privatenet
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data_test:/var/lib/postgresql/data

    minio:
        image: minio/minio
        container_name: kleinkram-minio
        volumes:
            - minio_data_test:/data
        environment:
            MINIO_ROOT_USER: ${MINIO_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
        entrypoint: sh
        # initialize buckets (see https://github.com/minio/minio/issues/4769#issuecomment-331033735)
        # and add service worker access key after startup of the minio server
        command: >
            -c "mkdir -p /data/${MINIO_BAG_BUCKET_NAME} &&
            mkdir -p /data/${MINIO_MCAP_BUCKET_NAME} && 
            mkdir -p /data/${MINIO_DB_BUCKET_NAME} &&
            /usr/bin/minio server --console-address ':9001' /data & 
            sleep 10 &&
            mc alias set myminio http://minio:9000 ${MINIO_USER} ${MINIO_PASSWORD} &&
            mc admin user svcacct add --access-key '${MINIO_ACCESS_KEY}' --secret-key '${MINIO_SECRET_KEY}' myminio ${MINIO_USER} || true &&
            echo 'minio is ready' &&
            sleep infinity"
        ports:
            - '127.0.0.1:9000:9000'
            - '127.0.0.1:9001:9001'
        networks:
            - webnet
            - privatenet

    frontend:
        image: rslethz/kleinkram:frontend-dev
        container_name: kleinkram-frontend

        build:
            context: .
            dockerfile: ./frontend/Dockerfile
            args:
                - QUASAR_ENDPOINT=${QUASAR_ENDPOINT}
        ports:
            - '8003:8003'

        env_file:
            - .env

        networks:
            - webnet

    redis:
        image: redis:latest
        container_name: kleinkram-redis
        ports:
            - '6379:6379'
        networks:
            - privatenet

    queue-consumer:
        image: rslethz/kleinkram:queue-consumer-latest
        container_name: kleinkram-queue-consumer
        hostname: 'DO_NOT_CHANGE'
        build:
            context: .
            dockerfile: queueConsumer/prod.Dockerfile
        volumes:
            # mount docker socket to access docker from within the container
            - /var/run/docker.sock:/var/run/docker.sock
        env_file:
            - .env
        networks:
            - privatenet
        depends_on:
            - database
            - loki

    prometheus:
        image: prom/prometheus
        container_name: kleinkram-prometheus
        volumes:
            - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - logging-prometheus-storage:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.enable-remote-write-receiver'
            - '--enable-feature=exemplar-storage'
            - '--enable-feature=native-histograms'
        ports:
            - '9090:9090'
        networks:
            - privatenet
            - webnet

    tempo:
        user: '0:0'
        image: grafana/tempo:latest
        container_name: kleinkram-tempo
        command: ['-config.file=/etc/tempo/tempo.yml']
        volumes:
            - ./observability/tempo/tempo.yml:/etc/tempo/tempo.yml
            - logging-tempo-data:/tmp/tempo
        ports:
            - '3200' # tempo
            - '4317' # otlp grpc
            - '4318' # otlp http
        networks:
            - privatenet
            - webnet

    loki:
        image: grafana/loki
        container_name: kleinkram-loki
        ports:
            - '3100:3100'
        command:
            - --config.file=/mnt/config/loki-config.yml
        volumes:
            - ./observability/loki/loki-config.yml:/mnt/config/loki-config.yml:ro
        networks:
            - privatenet
            - webnet

volumes:
    db_data_test:
    minio_data_test:
    logging-prometheus-storage:
    logging-tempo-data:
    vitepress_dist:
    node_modules:

networks:
    webnet:
    privatenet:
