version: '3.8'

services:
    main:
        image: rslethz/grandtour-datasets:api-server-dev
        container_name: api-server

        build:
            context: .
            dockerfile: ./backend/prod.Dockerfile

        ports:
            - 127.0.0.1:${SERVER_PORT}:${SERVER_PORT}

        env_file:
            - .env

        volumes:
            - swagger-spec:/usr/src/app/backend/docs

        networks:
            - webnet
            - privatenet

        environment:
            SEED: 'false'
            DEVBUILD: 'false'

        depends_on:
            - database

    database:
        image: postgres:13
        container_name: postgres_db

        ports:
            - '5432:5432'

        networks:
            - privatenet

        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}

        volumes:
            - postgres_db_data:/var/lib/postgresql/data

    minio:
        image: minio/minio
        container_name: minio_file_storage

        volumes:
            - minio_data:/data

        environment:
            MINIO_ROOT_USER: ${MINIO_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}

        command: >
            -c "mkdir -p /data/${MINIO_BAG_BUCKET_NAME} &&
            mkdir -p /data/${MINIO_MCAP_BUCKET_NAME} && 
            mkdir -p /data/${MINIO_DB_BUCKET_NAME} &&
            /usr/bin/minio server --console-address ':9001' /data & 
            sleep 10 &&
            mc alias set myminio http://minio:9000 ${MINIO_USER} ${MINIO_PASSWORD} &&
            mc admin user svcacct add --access-key '${MINIO_ACCESS_KEY}' --secret-key '${MINIO_SECRET_KEY}' myminio ${MINIO_USER} || true &&
            echo 'minio is ready' &&
            sleep infinity"

        ports:
            - '127.0.0.1:9000:9000' # file storage
            - '127.0.0.1:9001:9001' # management console
        networks:
            - webnet
            - privatenet

    frontend:
        image: rslethz/grandtour-datasets:vuejs_frontend-dev
        container_name: vuejs_frontend

        build:
            context: .
            dockerfile: ./frontend/Dockerfile
            args:
                - QUASAR_ENDPOINT=${QUASAR_ENDPOINT}

        ports:
            - '8003:80'

        networks:
            - webnet

    redis:
        image: redis:latest
        ports:
            - '6379:6379'
        networks:
            - privatenet

    bullconsumer:
        image: rslethz/grandtour-datasets:bull-consumer-dev
        container_name: bullconsumer
        build:
            context: .
            dockerfile: ./queueConsumer/prod.Dockerfile
        env_file:
            - .env
        networks:
            - privatenet
        depends_on:
            - database
            - loki
        volumes:
            # mount docker socket to access docker from within the container
            - /var/run/docker.sock:/var/run/docker.sock
    prometheus:
        image: prom/prometheus
        volumes:
            - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - logging-prometheus-storage:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.enable-remote-write-receiver'
        ports:
            - '9090:9090'
        networks:
            - privatenet

    tempo:
        user: '0:0'
        image: grafana/tempo:latest
        command: ['-config.file=/etc/tempo/tempo.yml']
        volumes:
            - ./observability/tempo/tempo.yml:/etc/tempo/tempo.yml
            - logging-tempo-data:/tmp/tempo
        ports:
            - '3200' # tempo
            - '4317' # otlp grpc
            - '4318' # otlp http
        networks:
            - privatenet

    loki:
        image: grafana/loki
        container_name: loki
        ports:
            - '3100:3100'
        command:
            - --config.file=/mnt/config/loki-config.yml
        volumes:
            - ./observability/loki/loki-config.yml:/mnt/config/loki-config.yml:ro
        networks:
            - privatenet

    grafana:
        image: grafana/grafana
        volumes:
            - logging-grafana-storage:/var/lib/grafana
            - ./observability/grafana/provisioning:/etc/grafana/provisioning

        environment:
            - GF_LOG_LEVEL=debug
        ports:
            - '9050:3000' # localhost:9050 for accessing grafana
        networks:
            - privatenet

    awt-docs:
        depends_on:
            - main
        image: rslethz/grandtour-datasets:docs-dev
        volumes:
            - swagger-spec:/app/src/docs/
        build:
            context: docs/.
            dockerfile: Dockerfile

    artifactUploader:
        image: rslethz/grandtour-datasets:artifact-uploader-latest-dev
        build:
            context: queueConsumer/src/artifactUpload
            dockerfile: Dockerfile

volumes:
    postgres_db_data:
    minio_data:
    logging-prometheus-storage:
    logging-grafana-storage:
    logging-tempo-data:
    swagger-spec:

networks:
    webnet:
    privatenet:
