version: '3.7'
services:
  main:
    image: rslethz/grandtour-datasets:api-server-latest
    container_name: API
    build:
      context: ./backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 127.0.0.1:${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env
    networks:
      - webnet
      - privatenet
    depends_on:
      - database


  database:
    image: postgres:13
    container_name: postgres_db
    ports:
      - '5432:5432'
    networks:
      - privatenet
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER:  ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server --console-address ":9001" /data
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    networks:
      - webnet

  fastapi:
    image: rslethz/grandtour-datasets:fastapi_api-latest

    container_name: fastapi
    build: ./bagHandler

    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - privatenet

  frontend:
    image: rslethz/grandtour-datasets:vuejs_frontend-latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - QUASAR_ENDPOINT=${QUASAR_ENDPOINT}
    container_name: vuejs_frontend
    ports:
      - "8003:80"
    env_file:
      - .env
    develop:
      watch:
        - action: sync+restart
          path: ./frontend
          target: /app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  bullconsumer:
    image: rslethz/grandtour-datasets:bull-consumer-latest
    container_name: bullconsumer
    build:
      context: ./queueConsumer
    volumes:
      - ./queueConsumer:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    networks:
      - privatenet
    depends_on:
      - database
volumes:
  db_data:
  minio_data:

networks:
  webnet:
  privatenet: