{
 "title": "Kleinkram Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "General Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Low Traces [duration >= 100ms]",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
     "targets": [
      {
       "filters": [
        { "id": "989412e5", "operator": "=", "scope": "span" },
        {
         "id": "service-name",
         "operator": "=",
         "scope": "resource",
         "tag": "service.name",
         "value": [ "backend" ],
         "valueType": "string"
        },
        {
         "id": "min-duration",
         "operator": ">",
         "tag": "duration",
         "value": "100ms",
         "valueType": "duration"
        }
       ],
       "limit": 20,
       "tableType": "traces"
      }
     ]
    },
    {
     "title": "Queue State",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 72 },
     "targets": [
      { "expr": "backend_active_jobs", "legendFormat": "active - {{queue}}" },
      { "expr": "backend_pending_jobs", "legendFormat": "pending - {{queue}}" }
     ]
    },
    {
     "title": "Backend Call Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 82 },
     "targets": [
      {
       "expr": "sum by (client, server)(rate(traces_service_graph_request_total{server=\"backend\"}[$__rate_interval]))"
      }
     ]
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{job=\"storage-job\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total S3 Ingress",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(SeaweedFS_s3_bucket_traffic_received_bytes_total)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Data Usage Growth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(SeaweedFS_s3_bucket_size_bytes)",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Number of Buckets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(SeaweedFS_s3_bucket_size_bytes)"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SeaweedFS_volumeServer_resource{type=\"all\"} - SeaweedFS_volumeServer_resource{type=\"free\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "SeaweedFS_volumeServer_resource{type=\"free\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Total S3 Egress",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(SeaweedFS_s3_bucket_traffic_sent_bytes_total)"
    }
   ]
  },
  {
   "title": "Number of Objects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(SeaweedFS_s3_bucket_object_count)"
    }
   ]
  },
  {
   "title": "S3 API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (type) (increase(SeaweedFS_s3_request_total[$__rate_interval]))",
     "legendFormat": "{{server,api}}"
    }
   ]
  },
  {
   "title": "S3 API Request Error Rate (4xx)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (type) (increase(SeaweedFS_s3_request_total{code=~\"4..\"}[$__rate_interval]))",
     "legendFormat": "{{server,api}}"
    }
   ]
  },
  {
   "title": "S3 API Request Error Rate (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (type) (increase(SeaweedFS_s3_request_total{code=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "{{server,api}}"
    }
   ]
  },
  {
   "title": "QueueConsumer Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "QueueConsumer Logs",
     "type": "logs",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 91 },
     "targets": [
      {
       "expr": "{job=\"queue-consumer\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "Backend Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backend Logs",
     "type": "logs",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 82 },
     "targets": [
      {
       "expr": "{job=\"backend\"} |= `` | json"
      }
     ]
    }
   ]
  },
  {
   "title": "Backend NodeJS Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "irate(process_cpu_user_seconds_total[2m]) * 100",
       "legendFormat": "User CPU - {{instance}}"
      },
      {
       "expr": "irate(process_cpu_system_seconds_total[2m]) * 100",
       "legendFormat": "Sys CPU - {{instance}}"
      }
     ]
    },
    {
     "title": "Event Loop Lag",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 10, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "nodejs_eventloop_lag_seconds", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Process Restart Times",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(changes(process_start_time_seconds[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Process Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "process_resident_memory_bytes", "legendFormat": "Process Memory - {{instance}}" },
      { "expr": "nodejs_heap_size_total_bytes", "legendFormat": "Heap Total - {{instance}}" },
      { "expr": "nodejs_heap_size_used_bytes", "legendFormat": "__auto" },
      { "expr": "nodejs_external_memory_bytes", "legendFormat": "External Memory - {{instance}}" }
     ]
    },
    {
     "title": "Active Handlers/Requests Total",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "nodejs_active_handles_total", "legendFormat": "Active Handler - {{instance}}" },
      { "expr": "nodejs_active_requests_total", "legendFormat": "Active Request - {{instance}}" }
     ]
    }
   ]
  }
 ]
}