scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 10s

    - job_name: 'tempo'
      scrape_interval: 10s
      static_configs:
          - targets: ['tempo:3200']

    - job_name: minio-job
      metrics_path: /minio/v2/metrics/cluster
      scrape_interval: 10s
      scheme: http
      static_configs:
          - targets: ['minio:9000']

    - job_name: minio-job-bucket
      scrape_interval: 10s
      metrics_path: /minio/v2/metrics/bucket
      scheme: http
      static_configs:
          - targets: ['minio:9000']

    - job_name: postgres-exporter
      scrape_interval: 10s
      scheme: http
      static_configs:
          - targets: ['postgres-exporter:9187']

    - job_name: 'backend'
      scrape_interval: 10s
      metrics_path: /metrics
      static_configs:
          - targets: ['main:3000']
