scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 1s

    - job_name: 'tempo'
      static_configs:
          - targets: ['tempo:3200']

    - job_name: 'backend'
      scrape_interval: 1s
      metrics_path: /metrics
      static_configs:
          - targets: ['main:3000']
