<template>
    <title-section title="Action Details">
        <template #tabs>
            <q-tabs
                v-model="tab"
                dense
                class="text-grey"
                align="left"
                active-color="primary"
            >
                <q-tab
                    name="template"
                    label="Action Template"
                    style="color: #222"
                />
                <q-tab
                    name="info"
                    label="Execution Details"
                    style="color: #222"
                />
                <q-tab
                    name="logs"
                    label="Logs"
                    style="color: #222"
                    :disable="!action?.logs || action?.logs.length === 0"
                >
                    <q-tooltip
                        v-if="!action?.logs || action?.logs.length === 0"
                    >
                        <span>No logs available</span>
                    </q-tooltip>
                </q-tab>
                <q-tab
                    name="auditLogs"
                    label="Audit Logs"
                    style="color: #222"
                    :disable="
                        !action?.auditLogs || action?.auditLogs.length === 0
                    "
                >
                    <q-tooltip
                        v-if="
                            !action?.auditLogs || action?.auditLogs.length === 0
                        "
                    >
                        <span>No audit logs available</span>
                    </q-tooltip>
                </q-tab>
            </q-tabs>
        </template>

        <template #buttons>
            <button-group>
                <q-btn
                    class="button-border"
                    flat
                    icon="sym_o_arrow_back"
                    label="Back to Actions"
                    @click="navigateBackToActions"
                />
                <q-btn
                    class="button-border"
                    flat
                    color="primary"
                    icon="sym_o_link"
                    label="Mission"
                    @click="openMission"
                >
                    <q-tooltip> Analyze Actions</q-tooltip>
                </q-btn>
            </button-group>
        </template>
    </title-section>

    <q-tab-panels v-model="tab" class="q-mt-lg" style="background: transparent">
        <q-tab-panel name="info">
            <ActionDetailsExecutionTab v-if="action" :action="action" />
        </q-tab-panel>

        <q-tab-panel name="logs">
            <p style="max-width: 650px; color: #525252; font-size: 0.8em">
                We capture the stdout and stderr of the action execution. In the
                following we list all the logs generated by the action container
                during the execution of the action.
            </p>

            <q-card
                class="q-pa-lg"
                style="background-color: #f4f4f4"
                flat
                bordered
            >
                <q-card-section class="flex column q-pa-none">
                    <div
                        v-for="log in action?.logs"
                        :key="log.timestamp.toISOString()"
                        class="flex justify-start q-pb-xs"
                        style="
                            font-family: monospace;
                            color: #222222;
                            font-size: 0.8em;
                        "
                    >
                        <template v-if="log.type == 'stdout'">
                            <span
                                class="q-pr-sm"
                                style="user-select: none; color: #525252"
                                >{{
                                    formatDate(new Date(log.timestamp), true)
                                }}</span
                            >
                            <span
                                class="q-pr-sm"
                                style="user-select: none; color: #525252"
                            >
                                [{{ log.type }}]
                            </span>

                            <span
                                style="margin-left: -250px; padding-left: 250px"
                            >
                                {{ log.message.replaceAll(' ', '\u00a0') }}
                            </span>
                        </template>

                        <template v-else>
                            <span
                                class="q-pr-sm"
                                style="user-select: none; color: #fd7c7cff"
                                >{{
                                    formatDate(new Date(log.timestamp), true)
                                }}</span
                            >
                            <span
                                class="q-pr-sm"
                                style="user-select: none; color: #fd7c7cff"
                            >
                                [{{ log.type }}]
                            </span>

                            <span
                                style="
                                    margin-left: -250px;
                                    padding-left: 250px;
                                    color: #ff3c3c;
                                "
                            >
                                {{ log.message.replaceAll(' ', '\u00a0') }}
                            </span>
                        </template>
                    </div>
                </q-card-section>
            </q-card>
        </q-tab-panel>

        <q-tab-panel name="auditLogs">
            <p style="max-width: 650px; color: #525252; font-size: 0.8em">
                Audit log help to understand which elements are being accessed
                by the action. This is useful for debugging and security
                purposes. In the following we list all endpoints called by the
                kleinkram CLI during the execution of the action.
            </p>

            <q-card
                class="q-pa-lg"
                style="background-color: #f4f4f4"
                flat
                bordered
            >
                <div
                    v-for="log in action?.auditLogs"
                    :key="log.url"
                    class="flex justify-start q-pb-xs"
                    style="
                        font-family: monospace;
                        color: #222222;
                        font-size: 0.8em;
                    "
                >
                    <span
                        class="q-pr-sm"
                        style="user-select: none; color: #525252"
                        >{{ log.method }}</span
                    >

                    <span>
                        {{ log.url }}
                    </span>
                </div>
            </q-card>
        </q-tab-panel>

        <q-tab-panel name="template">
            <ActionDetailsTemplateTab
                v-if="action"
                :template="action.template"
            />
        </q-tab-panel>
    </q-tab-panels>
</template>

<script setup lang="ts">
import { ArtifactState } from '@common/enum';
import ActionDetailsExecutionTab from 'components/actions/action-details-execution-tab.vue';
import ActionDetailsTemplateTab from 'components/actions/action-details-template-tab.vue';
import ButtonGroup from 'components/buttons/button-group.vue';
import TitleSection from 'components/title-section.vue';
import { useActionDetails } from 'src/composables/use-actions-queries';
import ROUTES from 'src/router/routes';
import { formatDate } from 'src/services/date-formating';
import { computed, ref } from 'vue';
import 'vue-json-pretty/lib/styles.css';
import { useRoute, useRouter } from 'vue-router';

const tab = ref('template');

const $route = useRoute();
const $router = useRouter();

const { data: action } = useActionDetails(
    computed(() => $route.params.id as string),
);

const artifactState = computed(() => {
    switch (action.value?.artifacts ?? ArtifactState.ERROR) {
        case ArtifactState.UPLOADING: {
            return 'Uploading...';
        }
        case ArtifactState.ERROR: {
            return 'N/A';
        }
        case ArtifactState.AWAITING_ACTION: {
            return 'Waiting action completion...';
        }
        // No default
    }
    return 'N/A';
});

const openArtifact = (): void => {
    if (action.value === undefined) return;
    window.open(action.value.artifactUrl, '_blank');
};

const openMission = async (): Promise<void> => {
    if (action.value === undefined) return;

    await $router.push({
        name: ROUTES.FILES.routeName,
        params: {
            projectUuid: action.value.mission.project.uuid,
            missionUuid: action.value.mission.uuid,
        },
    });
};

const navigateBackToActions = async (): Promise<void> => {
    const previousPath = window.history.state?.back as string | undefined;

    // If we came from the actions list (any tab), go back to preserve filters/state
    if (previousPath?.includes('/actions')) {
        $router.back();
        return;
    }

    // Fallback: Go to Executions tab with current action's scope
    if (action.value) {
        await $router.push({
            name: ROUTES.ACTION.name,
            params: { tab: 'runs' },
            query: {
                projectUuid: action.value.mission.project.uuid,
                missionUuid: action.value.mission.uuid,
                sortBy: 'createdAt',
                descending: 'true',
            },
        });
    } else {
        // Safety fallback
        await $router.push({ name: ROUTES.ACTION.name });
    }
};
</script>

<style>
/* Styles removed as table is no longer used */
</style>
