name: Docker Image CI (GrandTour Datasets)

on:
    push:
        branches: ['dev']

jobs:
    kleinkram_build:
        environment: 'BuildEnv'
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Cache Yarn
              id: yarn-cache
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cache/yarn/v6
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - working-directory: .
              name: Build the Docker compose
              run: docker compose -f docker-compose.dev.yml build
              env:
                  QUASAR_ENDPOINT: ${{ vars.QUASAR_ENDPOINT_DEV }}
            - working-directory: .
              name: push the docker image
              run: docker compose -f docker-compose.dev.yml push
