name: Docker Image CI (GrandTour Datasets)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  GrandTourBuild:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - working-directory: .
        name: Build the Docker compose
        run: docker compose up --build
      - working-directory: .
        name: push the docker image
        run: docker compose push

        
