name: Docker Image CI (GrandTour Datasets)

on:
    push:
        branches: ['main']

jobs:
    GrandTourBuild:
        environment: 'BuildEnv'
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - working-directory: .
              name: Build the Docker compose
              run: docker compose -f docker-compose.prod.yml build
              env:
                  QUASAR_ENDPOINT: ${{ vars.QUASAR_ENDPOINT }}
            - working-directory: .
              name: push the docker -f docker-compose.prod.yml image
              run: docker compose push
