name: Lint

on:
    push:
        branches:
            - dev
        paths:
            - 'cli/**'

jobs:
    lint:
        runs-on: [self-hosted, linux]
        steps:
            - uses: actions/checkout@v4
            - uses: psf/black@stable
