name: Lint

on:
    push:
        branches:
            - dev
        paths:
            - 'CLI/**'

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: psf/black@stable
