name: Lint

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'CLI/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable