name: Test The Application

on:
    pull_request:
        branches:
            - main
            - dev

jobs:
    test_API:
        runs-on: [self-hosted, linux]

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4.3.0
              with:
                  node-version: '22'

            - name: install dependencies
              run: yarn install --immutable

            - name: build_stack
              run: docker compose -f docker-compose.testing.yml build

            - name: launch_stack
              working-directory: ./backend
              run: |
                  docker compose -f ../docker-compose.testing.yml up -d
                  SECONDS=0
                  TIMEOUT=60
                  while [ ! -f ./.endpoints/__generated__endpoints.json ]; do
                      if [ $SECONDS -ge $TIMEOUT ]; then
                          echo "Timeout reached: __generated__endpoints.json not found"
                          exit 1
                      fi
                      sleep 1
                      echo "waiting for endpoints"
                  done
                  yarn test
