name: Test The Application

on:
    pull_request:

jobs:
    test_API:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4.0.3
              with:
                  node-version: '22'

            - name: install dependencies
              run: yarn install --immutable

            - name: build_stack
              run: docker compose -f docker-compose.testing.yml build

            - name: launch_stack
              working-directory: ./backend
              run: |
                  docker compose -f ../docker-compose.testing.yml up -d
                  SECONDS=0
                  TIMEOUT=60
                  FILE_FOUND=false
                  DIRECTORIES=(./ ../ ./src ./dist)  # List directories to check
                  while [ $SECONDS -lt $TIMEOUT ]; do
                      for DIR in "${DIRECTORIES[@]}"; do
                          FILE_PATH="$DIR/__generated__endpoints.json"
                          echo "Looking for $FILE_PATH"
                          if [ -f "$FILE_PATH" ]; then
                              echo "File found: $FILE_PATH"
                              FILE_FOUND=true
                              break
                          fi
                      done

                      if [ "$FILE_FOUND" = true ]; then
                          break
                      fi

                      sleep 1
                      echo "waiting for endpoints"
                  done

                  if [ "$FILE_FOUND" = false ]; then
                      echo "Timeout reached: __generated__endpoints.json not found"
                      exit 1
                  fi

                  yarn test
