name: Build and Deploy CLI Tool

on:
    push:
        branches:
            - main
            - dev
        paths:
            - 'cli/**'

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.11' # Match your project's required Python version

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install build twine

            - name: Run release script in dev mode to set __local__ False
              if: github.ref == 'refs/heads/dev'
              run: |
                  python .github/scripts/release.py --dev

            - name: Run release script to set __local__ False
              if: github.ref == 'refs/heads/main'
              run: |
                  python .github/scripts/release.py

            - name: Build package
              run: |
                  cd cli
                  python -m build

            - name: Publish to PyPI
              uses: pypa/gh-action-pypi-publish@v1.10.3
              with:
                  user: __token__
                  password: ${{ secrets.PYPI_API_TOKEN }}
                  package: cli/dist/*
                  packages_dir: cli/dist
