name: Build and Deploy CLI Tool

on:
  push:
    paths:
      - 'CLI/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Match your project's required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatchling twine bumpversion-toml

      - name: Generate consts.py
        run: |
          echo "API_URL='https://api.datasets.leggedrobotics.com'" > CLI/src/ETH_GTD_cli/consts.py

      - name: Increment version and build package
        run: |
          bumpversion-toml patch --config-file CLI/pyproject.toml
          python3 -m build          

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
